apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abs
  namespace: abs
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  defaultBackend:
    service:
      name: abs
      port:
        name: http
  ingressClassName: external
  rules:
  - host: &host audiobookshelf.ak-online.be
    http:
      paths:
      - backend:
          service:
            name: abs
            port:
              name: http
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - *host
    secretName: abs-tls
