apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abs-config
  namespace: abs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: zfs-quick
  resources:
    requests:
      storage: 5Gi
