resources:
  - 10-cnpg-system-namespace.yaml

helmCharts:
  - releaseName: cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    name: cloudnative-pg
    version: 0.26.1
    skipTests: true

namespace: cnpg-system
