resources:
  - _cert-manager
  - _cnpg
  - _external-dns
  - _metallb-system
  - _reloader
  - _sops
  - _zfs-provisioner
  - auth
  - elk
  - grafana
  - grocy
  - immich
  - influx
  - ingress-nginx/
  - kube-system
  - kuma
  - ldap
  - magicmirror
  - netbox
  - patchman
  - vault
  - x11
  - zigbee2mqtt
