resources:
  - namespace-auth.yaml

  - secrets.enc.yaml

  - cluster-pg-keycloak.yaml
  - db-backup-store.yaml
  - db-scheduledbackup.yaml

  - certificate-keycloak.yaml
  # deploy keycloak operator
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.4.5/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.4.5/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.4.5/kubernetes/kubernetes.yml
  # deploy the custom resource
  - keycloak.yaml
namespace: auth
