resources:
  - 00_ns.yaml
  - 01_pvc.yaml
  - secrets.enc.yaml
  - 03_deployment.yaml
  - 04_svc.yaml
  - 05_ingress.yaml

configMapGenerator:
    - name: grafana-config
      files:
        - config/grafana.ini
      options:
        disableNameSuffixHash: true
