apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: grafana
  namespace: grafana
spec:
  secretTemplates:
    - name: grafana-env-secrets
      stringData:
        GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:Ecjma+y73DjhFE9K4WlsTpNXXX3y1uBae0PXGoD/YVw9Kak+6/tYm8ZdOhIFJeiVB5vAXpnLiGPWoXPTU/uy8WgH1id0uQXeISU=,iv:7MPFqXO8uIPHeHxSi/KFfoseAEA/Mpa2dKOl8Ag18Hc=,tag:Cq8CFsyTADXYGAiMT9rojw==,type:str]
        GF_SECURITY_SECRET_KEY: ENC[AES256_GCM,data:ukwniu6l4UcaPiAQVpM8WigQv6Te,iv:BDOvubdGbk9eh8yUelUo8Hz7szZexdxZSUFbyaoRUC0=,tag:72QjIlR83dSaGir9d91Fsg==,type:str]
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Fa/hva5rpK8wkUWhnKHgv3z0vPi7wz3Qkb4A2ittHmk=,iv:V6I3wNHRdRw9oqU05kquSJCQuDqreVx4cdw1f96+7m4=,tag:pHHe4xXq1jn5fPXd2JnOLQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1pfxd6zqm4x755qpxd2h4fl5uqnu07hrpyv2cstdey0lg5lc5x47qzsvrn5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZGoycHREczRSSkZNNkk5
        aXRBdzBJSGloMkNZSzVFMGlkVXpvcmJSYWlFCjhqd0x5ODZocUhDeDJEaWtJajUr
        ZWVmWTI0c2hmMHc0dWpBNWZRYkpyelEKLS0tIFlxd0c0eURsdU9UbTluOWRZcjhu
        eTYzV1VRTjZYc1M3aGxUNTBpeXlGdjgKI5m83ng1gYd7BLfxQu8TfT0ScL/QOvBN
        SU/NzfUG4puUgs5kZdLzOpNLVasSXO2sciM03Sm11/5U5DhflP2svw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-16T14:17:55Z"
  mac: ENC[AES256_GCM,data:kBJt3mA/rT1RNF5bayE5TkeTSn47LK6oktlHIeZz9vey3kgHuMiVWZheXcLj50FjC9WVi0zS5/Ig5WPgPWM9gjntgCo4QkpvKwJRtaRfNABeQWJSVrWJLURDyPS8DYijdyRnWokY2G0dP8KqkcTyD3dqn6pm3rCW1NegePCOxb4=,iv:An9PbsktWy9A+cO667Z3KPio4xv0vmTPSrpVn1kutT8=,tag:mTccrjqLbTF+0E61AQp7cQ==,type:str]
  pgp:
    - created_at: "2024-05-01T14:05:47Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAz9aZqoHT9PNAQ//VAp3RbDnrXekINqMilrGIiMAOS6HjNJQr/ueGgpxvzAt
        yNztUn3aZIISVgpPEdBAKeuh2jfwvCZlobAXYMnAwrY/Aa0Ei+Ibo1h8RbCSQTeW
        WRadaTREYXW/GQ7ZdxzUQ+8Zyt8lQt6ObmjorAVDolPOdYygVCkVPoY9/TFhNcz6
        U+x1xQfKYb4hctry8LvwZMeqzOmx+cKKqDBVxKfgp+3hrlVNCvsU9W1BFo9rN49f
        126uIcLfnWcrSwzlUaZCRS+gAJFbm9JSEohvpnS+tg6m+hPoZ3Gn6F0QV4BA2JJ+
        Hswiy9qF3brFNikXMPwOCpj6g8143ZgTfS470d8I+I9iRNtSgQOBkZWaozYh73ZX
        im+GrJmdvUA/8q24J55bmucN+hhxYxhwkisM7/OD7JMOnrry7A324EvBRWF9yiAh
        axHOxMpmGYnAz8+yJxBSGDbkC93RVFw7byawMYXcT2gI7mb0rmHRZ5tWNnpiWXzN
        oFaCdTwTYf6uSgoB3m7uk2QA5smLleX/8ZI+6iUQZXDsZ1ISOzl5JbNKF9TMc6+c
        g/E5NstE13nJAN1/qbuAiNeDTJvVjt94qiNkfVHf+2wQFvQnAqX6o88XFNRb0eOO
        ZLrqLfmz9zsJgC0sYYJE8WEhoM7sdeqaf6IvjkjC033852fFfWnpQ6HGdLpdNbTS
        XgE1ADFeXNdh3IGzranKxIrWrLKd4RRhV/GAywtidiTisIj9mWJUsP+CNzFmbalk
        Pg/Q5P35ZvA1ubA4JsgYNLDOVYI4qu77LIaMTo/aVRe/06muWdqLfdY1v+KWIBQ=
        =gVwk
        -----END PGP MESSAGE-----
      fp: 6528912C6687A3E2
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
