apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://api.immich.app"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,X-LANG,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Api-Key,X-Device-Id,Access-Control-Allow-Origin"
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: server
  name: immich-server
  namespace: immich
spec:
  ingressClassName: external
  rules:
  - host: immich.ak-online.be
    http:
      paths:
      - backend:
          service:
            name: immich-server
            port:
              number: 2283
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - immich.ak-online.be
    secretName: tls-immich
