resources:
  - namespace-immich.yaml
  - db.yaml
  - secrets.enc.yaml
  - db-backup-store.yaml
  - db-scheduledbackup.yaml

  - deployment-immich-server.yaml
  - service-immich-server.yaml

  - deployment-immich-worker.yaml
  - deployment-immich-machine-learning.yaml
  - service-immich-machine-learning.yaml

  - deployment-valkey.yaml
  - persistentvolumeclaim-valkey.yaml
  - service-valkey.yaml

  - ingress-immich-server.yaml

namespace: immich
