resources:
  - namespace-immich.yaml
  - db.yaml

  - deployment-immich-server.yaml
  - persistentvolume-immich-pv.yaml
  - persistentvolumeclaim-immich-pvc.yaml
  - persistentvolumeclaim-immich-valkey.yaml
  - service-immich-server.yaml

  - deployment-immich-machine-learning.yaml
  - service-immich-machine-learning.yaml

  - deployment-immich-valkey.yaml
  - service-immich-valkey.yaml

  - ingress-immich-server.yaml

namespace: immich
