resources:
  - namespace-vault.yaml

  - secrets.enc.yaml

  - cluster-pg-vault.yaml
  - db-backup-store.yaml
  - db-scheduledbackup.yaml

  - pvc-vault.yaml
  - configmap-vault-config.yaml
  - deployment-vault.yaml
  - service-vault.yaml

  - ingress-vault.yaml

namespace: vault
